#!/bin/sh
# Generated by `switchboard init`. Safe to delete; it will come back
# on the next run. If you edit it, `init` will leave it alone from
# then on and tell you so.
export SWITCHBOARD_URL=https://switchboard.lucille-ai.com; export SWITCHBOARD_WORKSPACE=gald33/roadmap-core;
if command -v switchboard >/dev/null 2>&1; then
  sb() { switchboard "$@"; }
elif command -v uvx >/dev/null 2>&1; then
  sb() { uvx --from 'agent-switchboard[crypto]' switchboard "$@"; }
else
  echo 'switchboard: switchboard not found and uvx unavailable; pip install '"'"'agent-switchboard[crypto]'"'"'' >&2
  exit 0
fi
holder="$(sb --json whoami | python -c 'import sys,json;print(json.load(sys.stdin)["agent_id"])')"
sb --json claims --holder "$holder" | python -c 'import sys,json;[print(l["resource"]) for l in json.load(sys.stdin)]' | while IFS= read -r resource; do sb -q release "$resource"; done
