#!/usr/bin/env python3
"""Roadmap work-item CLI — see ``roadmap/README.md``.

The store is the ``roadmap_items`` table, reached over the admin API. The
agent-facing artifact is ``roadmap/ROADMAP.md``, generated by ``sync`` and
committed, so a coding agent in a checkout can read the backlog with no DB
access, no admin JWT, and no network.

Two sources, one renderer:

  db     — the live graph via ``GET /admin/roadmap`` (needs LUCILLE_ADMIN_JWT)
  files  — ``roadmap/items/*.yaml``, the seed/offline authoring format

Both render through ``roadmap_core.graph``, loaded by path precisely so the CLI
needs none of the backend's dependencies. Same logic in the API and in the
markdown, or the file starts lying about what is ready.

The two sources drift, and the drift is invisible from either side alone:
``validate`` checks one source in isolation, and the CI sync guard compares two
*committed* artifacts that agree with each other while both disagree with the
store. So ``diff`` compares them directly and ``pull`` closes the gap the same
way ``push`` closes the other one.

Commands
    sync     regenerate roadmap/ROADMAP.md   (--source db|files)
    push     upload roadmap/items/*.yaml into the DB (prose + edges; NOT status)
    pull     write DB-only items + live claims back into roadmap/items/*.yaml
    diff     report where the DB and the committed files disagree
    prune    delete done items from the store AND the files (README rule 4)
    list     everything grouped by status
    ready    only what is startable now
    show     one item with its dependency chain
    claim    stake an item (one DB transaction — races cannot both win)
    status   move an item's status deliberately (the store owns that field)
    release  give it back
    validate schema, dangling deps, cycles

State fields — ``status`` and the claim — are the store's, and a file's value
for them is honored when the item is first filed and ignored afterwards. A
checkout is a snapshot; where an item *is* is not something a snapshot can
assert. ``push`` from files that predated a ``prune`` is what taught this: it
resurrected merged work as ``ready`` and silently un-started everything behind
it, because ``done`` is the one status the graph cannot re-derive.

``priority`` is NOT a state field. It is a judgement about what matters, so it is
authored in YAML, reviewed in a diff and uploaded by ``push`` — the same row of
the table as ``blocked_on`` and ``defer_reason``. It is the sort key ``ready``,
``list`` and the generated markdown all order by, ahead of the item key.
"""

from __future__ import annotations

import argparse
import contextlib
import json
import os
import re
import shutil
import subprocess
import sys
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any


def _repo_root() -> Path:
    """The project this CLI is driving.

    It used to be `__file__`'s grandparent, which was exactly right while the
    only copy of this file lived at `<repo>/scripts/roadmap.py`. Now the file
    ships inside the wheel, so `__file__` points into site-packages and that
    rule would resolve every path into somebody's virtualenv.

    So: an explicit `ROADMAP_REPO_ROOT` wins (Lucille's `scripts/roadmap.py`
    shim sets it, which is what keeps its layout working unchanged), then the
    nearest ancestor of the working directory that actually contains a
    `roadmap/` directory, then the working directory itself.

    Walking up matters more than it looks. `push` reports *"no item files to
    push"* when it is pointed at a directory that is not yours, which reads
    exactly like an empty backlog — so being run from a subdirectory would look
    like having nothing to do rather than like an error.
    """
    pinned = os.environ.get("ROADMAP_REPO_ROOT")
    if pinned:
        return Path(pinned).resolve()
    here = Path.cwd().resolve()
    # `roadmap/items` and `.git`, and deliberately NOT bare `roadmap/`.
    # `roadmap/` is a directory this tool CREATES — the store lands at
    # `roadmap/roadmap.db` — so keying on it means one command run from the
    # wrong directory mints the marker that makes that directory look like a
    # project root forever afterwards. Measured, not theorised: a single
    # `roadmap ready` in a subdirectory made every later command there resolve
    # to the subdirectory and read an empty backlog.
    #
    # Both markers are things a person makes: `roadmap/items` is where items
    # are authored, `.git` is where the project begins.
    for marker in (Path("roadmap") / "items", Path(".git")):
        for candidate in (here, *here.parents):
            if (candidate / marker).exists():
                return candidate
    return here


REPO_ROOT = _repo_root()
ITEMS_DIR = REPO_ROOT / "roadmap" / "items"
ARCS_DIR = REPO_ROOT / "roadmap" / "arcs"
GENERATED_MD = REPO_ROOT / "roadmap" / "ROADMAP.md"
# At the repo root, not under roadmap/, because that is where it has always been
# and every doc, CLAUDE.md included, links to `ARCS.md`. Moving a generated file
# is a rename that breaks references; generating it in place is not.
GENERATED_ARCS_MD = REPO_ROOT / "ARCS.md"
# The graph and the stores are this file's own siblings now, so they are simply
# imported. They used to be loaded BY PATH from `<repo>/roadmap-core/`, which
# was what let the CLI run in a bare checkout with nothing installed — and that
# property survives the move intact, because a plain directory on `sys.path` is
# importable without being installed. Lucille's shim prepends its checkout, so a
# checkout's own copy still wins over whatever happens to be in site-packages.

# Where a standalone checkout keeps its own store, and which store the write
# commands talk to by default. Both are read from the environment so another
# repository sets them once instead of passing --source on every invocation;
# unset, everything behaves exactly as it did before stores existed.
# Anchored to the repo root, not to the working directory. `store.DEFAULT_PATH`
# is the relative `roadmap/roadmap.db`, which is right for a library whose
# caller passes a path and wrong for a CLI you can run from anywhere: it made
# `roadmap claim` in a subdirectory open a SECOND store and take the claim
# there, so two agents in one checkout could each hold the same item and the
# transaction that is supposed to arbitrate never saw the other.
ROADMAP_STORE_PATH = (
    os.environ.get("ROADMAP_STORE") or str(REPO_ROOT / "roadmap" / "roadmap.db")
)
_ENV_SOURCE = os.environ.get("ROADMAP_SOURCE") or None

_ID_RE = re.compile(r"^[a-z0-9]+(-[a-z0-9]+)*$")
DEFAULT_BACKEND = os.environ.get("LUCILLE_BACKEND_URL", "")

# Switchboard write exclusion (roadmap item switchboard-agent-coordination).
# Advisory only — see switchboard_write_lock's docstring for what "advisory"
# buys and costs here. Same default-and-override shape as DEFAULT_BACKEND above,
# matching the values committed in .mcp.json.
SWITCHBOARD_URL = os.environ.get("SWITCHBOARD_URL", "")
SWITCHBOARD_WORKSPACE = os.environ.get("SWITCHBOARD_WORKSPACE", "")
# SECONDS, and deliberately so. This lease covers the read-modify-write of one
# item file and nothing else — it is released the moment that write returns, and
# the TTL is only the ceiling for a session that dies mid-write. It used to be
# 14400 (four hours), sized to the WORK rather than to the WRITE, which is the
# thing a lease cannot express: a lease means "a live process holds this", so one
# sized to outlive its holder's death is a lock, and a lock nobody can clear is
# the leaked claim Switchboard exists to eliminate. See the header comment below
# for where the other two questions that constant used to answer now live.
SWITCHBOARD_LEASE_TTL = int(os.environ.get("LUCILLE_ROADMAP_LEASE_TTL", "30"))


from . import graph  # noqa: E402  (after the constants it does not use)

# `graph` and `stores` are siblings of this module now, so they are imported
# rather than located. They used to be loaded BY PATH out of
# `<repo>/roadmap-core/`, because that was the only way this file — which lived
# at `<repo>/scripts/roadmap.py`, outside the package — could reach them with
# nothing installed.
#
# The property that dance protected is not lost: a plain directory on `sys.path`
# is importable without being installed, so a bare checkout still works, and
# Lucille's `scripts/roadmap.py` shim prepends its own `roadmap-core/` so the
# checkout's copy still wins over anything in site-packages. What is gone is the
# failure it kept reintroducing — a path that only existed in one repository's
# layout, which is what stopped an adopter with the package correctly installed
# from running a single command.


def _stores() -> Any:
    """The store implementations, imported lazily.

    Still lazy, and for the reason it always was: the read paths must keep
    working when the store cannot be built at all. `list`, `ready` and `show`
    against `roadmap/items/*.yaml` are what an agent needs first, and they
    should not fail on an import they never use.
    """
    from . import stores

    return stores


def _write_source(args: argparse.Namespace) -> str:
    """Which store a write command should use, tolerating a caller that predates
    the flag.

    Defaulting to ``db`` when the attribute is absent rather than requiring it:
    these functions are called directly by tests and by other scripts that build
    a ``Namespace`` by hand, and a new flag should not make an old caller raise
    ``AttributeError`` on a code path it never asked to change.
    """
    return getattr(args, "source", "db")


def store_for(source: str) -> Any:
    """The store a command should talk to.

    `local` is a SQLite file and needs nothing else; `db` is Lucille's admin API
    and is handed `_api` as its caller — the ApiStore itself holds no token and
    no URL, so how this authenticates stays entirely on this side of the seam.
    """
    stores = _stores()
    if source == "local":
        return stores.LocalStore(ROADMAP_STORE_PATH)
    return stores.ApiStore(_api)


def current_branch() -> str:
    try:
        out = subprocess.run(
            ["git", "rev-parse", "--abbrev-ref", "HEAD"],
            cwd=REPO_ROOT, capture_output=True, text=True, timeout=10,
        )
        return out.stdout.strip() or "unknown"
    except (OSError, subprocess.SubprocessError):
        return "unknown"


# --- switchboard write exclusion ----------------------------------------------
#
# LEASE THE WRITE, NOT THE WORK.
#
# One item's claim state is asked three different questions, and a single
# long-lived lease used to answer all three badly. They are separated here:
#
#   "this item is mine for the next three days"  -> the committed item file.
#                                                   Durable. Never expires.
#   "nobody else read-modify-write this item     -> a Switchboard lease, held
#    while I am"                                    for SECONDS, below.
#   "am I still breathing on what I own"         -> roster/presence. Expiry is
#                                                   CORRECT there, not a bug.
#
# A lease means "a LIVE PROCESS holds this" — renewal is a side effect of the
# holder's heartbeat. Sized to the work rather than the write it stops being a
# lease and becomes a lock that survives its holder's death, which is the exact
# leaked claim Switchboard exists to eliminate, and it fails silently: a
# four-hour lease whose holder died in minute one blocks the item for the rest
# of the window and nothing ever asks.
#
# THE ROADMAP STORE STAYS THE ONLY AUTHORITY on who holds an item. This lease
# does not decide a claim and is never read back to validate one; it serializes
# the file write so two sessions cannot interleave a read-modify-write of the
# same YAML. Until the store is retired, Postgres still settles the cross-session
# race — this is the primitive that would replace it, proven in place first.
#
# Nothing here may block or fail a `claim`/`release`. Advisory: nudge dropped,
# roadmap claim wins. It degrades LOUDLY — every failure path prints — because a
# silent no-op is indistinguishable from working (this project's own CI
# announced nothing for a full day inside green builds, behind a `|| true`).
#
# Shells out to the `switchboard` CLI rather than re-implementing its HTTP calls,
# on purpose: every environment that runs `roadmap.py claim` interactively
# already has it (SessionStart hook, per CLAUDE.md).


def _switchboard_cli(
    *args: str, agent_id: str | None = None, timeout: float = 15.0
) -> subprocess.CompletedProcess | None:
    """Run one `switchboard` subcommand. Returns None if the CLI is not on
    PATH, if it errors, or if it does not answer in time — never raises, and
    never distinguishes those causes to the caller because none of them are
    actionable here beyond "the lease did not happen this time"."""
    if shutil.which("switchboard") is None:
        return None
    # An UNPINNED switchboard identity is derived from repo + branch + session,
    # so the working directory is part of who you are: shelling out from any cwd
    # other than the agent's repo root records the lease under a different id
    # than the agent announces as, and the lease is held by a ghost. Pin it —
    # see _switchboard_agent_id for why the pin must be per-session and NOT the
    # branch, and for how the reaper finds a holder instead.
    pin = ["--agent-id", agent_id] if agent_id else []
    try:
        return subprocess.run(
            # Global flags before the subcommand — the CLI does not accept
            # them after it (a documented gotcha this repo has hit more than
            # once; see CLAUDE.md's Switchboard section).
            ["switchboard", "--url", SWITCHBOARD_URL, "-w", SWITCHBOARD_WORKSPACE,
             *pin, *args],
            capture_output=True, text=True, timeout=timeout,
        )
    except (OSError, subprocess.SubprocessError):
        return None


def _switchboard_resource(key: str) -> str:
    return f"roadmap/{key}"


def _switchboard_agent_id() -> str:
    """A cwd-stable identity for this process's leases, DISTINCT per session.

    Both halves matter, and they pull against each other:

    *Stable* rules out letting the CLI derive one, because an unpinned identity
    includes the working directory — shelling out from a different cwd records
    the lease under an id the holder does not recognise as itself.

    *Distinct* rules out the obvious fix of pinning to the branch. Every session
    on that branch would then BE the same agent: sharing one read cursor, and
    able to release each other's leases — by construction, not by impersonation.
    That is the two-editor-tabs collision Switchboard's own session suffix exists
    to prevent, and it would land here as "my write lock vanished mid-write".

    So: honour the session's own pin when it has one, and otherwise mint an id
    that is unique to this process. Per-process is the right grain precisely
    because the lock is acquired and released inside one process — two concurrent
    `roadmap.py` runs SHOULD exclude each other, which is the whole point.

    Note this is not how the reaper will find a claim's holder. An agent id is
    session-scoped, so a session that legitimately restarts gets a new one and a
    multi-day claim would point at a dead id. Reconciliation runs through the
    branch, which the roster publishes as its own field and which survives a
    restart. This id is diagnostic detail; `claim.by` remains the key.
    """
    pinned = os.environ.get("SWITCHBOARD_AGENT_ID", "").strip()
    return pinned or f"roadmap-{current_branch()}-{os.getpid()}"


@contextlib.contextmanager
def switchboard_write_lock(key: str) -> Any:
    """Serialize the read-modify-write of `roadmap/items/<key>.yaml`.

    Acquired immediately before the write and released the moment it returns,
    so the lease is live for the duration of a file edit and not a working
    session. Best-effort throughout: a lock that cannot be taken is reported
    and the write proceeds, because the store has already decided the claim and
    an advisory layer must never turn a won claim into a failure.

    Takes no holder argument on purpose. The identity is this process's
    (`_switchboard_agent_id`), and letting a caller pass one is how it acquired
    a branch — i.e. an identity shared with every other session on that branch,
    each able to release the others' locks.
    """
    if not os.environ.get("SWITCHBOARD_TOKEN"):
        yield
        return
    resource = _switchboard_resource(key)
    who = _switchboard_agent_id()
    # The branch goes in the NOTE, never in the identity. A note is descriptive
    # and cannot collide; an identity is a key and can — two sessions sharing one
    # would be re-entrant for each other's locks, i.e. excluded from nothing, in
    # exactly the case this lock exists for. Carrying it here still gives anyone
    # reading `switchboard claims` (and §3's reaper, if it wants corroboration)
    # the link from a live lock back to the `claim.by` that owns the item.
    result = _switchboard_cli(
        "claim", resource,
        "--note", f"roadmap file write: {key} (claim.by={current_branch()})",
        "--ttl", str(SWITCHBOARD_LEASE_TTL),
        agent_id=who,
    )
    if result is None:
        print(
            "note: no switchboard write lock (CLI missing, unreachable, or timed out) "
            "— writing anyway; the store already settled this claim.",
            file=sys.stderr,
        )
    elif result.returncode != 0:
        print(
            f"note: could not take the switchboard write lock on {resource} "
            f"({result.stderr.strip() or result.stdout.strip() or 'unknown error'}). "
            f"Writing anyway — advisory only. If another session is mid-write on this "
            f"item, re-run `roadmap.py pull` afterwards and check the file.",
            file=sys.stderr,
        )
    try:
        yield
    finally:
        # Released immediately: holding it past the write is the very mistake
        # this section exists to undo. The TTL is only the ceiling for a session
        # that dies between the two calls.
        done = _switchboard_cli("release", resource, agent_id=who)
        if done is not None and done.returncode != 0:
            print(
                f"note: could not release the switchboard write lock on {resource} "
                f"({done.stderr.strip() or 'unknown error'}). It expires on its own "
                f"within {SWITCHBOARD_LEASE_TTL}s.",
                file=sys.stderr,
            )


# --- sources -----------------------------------------------------------------


def _truncated_refs(text: str) -> list[str]:
    """Ref lines that YAML will silently cut short at an unquoted ``" #"``.

    `_yaml_scalar` quotes on `" #"` so anything *written* by this script is
    safe, but item files are also hand-authored, and there the loss is total
    and silent: `- PR #861` parses to `PR`, `validate` passes because it never
    inspects ref contents, and `diff` passes because it deliberately does not
    compare refs. Five refs reached prod that way on 2026-07-31.

    So this is checked against the raw text, before PyYAML has thrown the
    information away — by then there is nothing left to detect. Scoped to the
    ``refs:`` block: a ``#`` inside the ``evidence`` block scalar is literal
    and fine, which is why this cannot just scan the whole file.
    """
    bad: list[str] = []
    in_refs = False
    for line in text.splitlines():
        if not line.startswith((" ", "\t", "-")) and line.strip():
            in_refs = line.split(":", 1)[0].strip() == "refs"
            continue
        if not in_refs:
            continue
        entry = line.strip()
        if not entry.startswith("- "):
            continue
        scalar = entry[2:].strip()
        if scalar[:1] in ("'", '"'):
            continue
        if " #" in scalar:
            bad.append(scalar)
    return bad


def load_from_files() -> dict[str, dict[str, Any]]:
    """Parse ``roadmap/items/*.yaml``. Raises on the first malformed file — a
    half-loaded graph is worse than no graph."""
    try:
        import yaml
    except ImportError:  # pragma: no cover
        raise SystemExit("PyYAML required for --source files (pip install pyyaml)") from None
    by_key: dict[str, dict[str, Any]] = {}
    if not ITEMS_DIR.is_dir():
        return by_key
    for path in sorted(ITEMS_DIR.glob("*.yaml")):
        text = path.read_text()
        truncated = _truncated_refs(text)
        if truncated:
            raise SystemExit(
                f"{path}: ref(s) will silently truncate at ' #' — "
                + "; ".join(f"{s!r} loads as {s.split(' #', 1)[0]!r}" for s in truncated)
                + "\nQuote them: - 'PR #861'"
            )
        try:
            raw = yaml.safe_load(text) or {}
        except yaml.YAMLError as exc:
            raise SystemExit(f"{path}: invalid YAML: {exc}") from exc
        if not isinstance(raw, dict):
            raise SystemExit(f"{path}: expected a mapping at the top level")
        key = str(raw.get("id") or raw.get("key") or "")
        if key != path.stem:
            raise SystemExit(f"{path}: id {key!r} does not match filename stem {path.stem!r}")
        if not _ID_RE.match(key):
            raise SystemExit(f"{path}: id {key!r} is not kebab-case")
        claim = raw.get("claim") or {}
        by_key[key] = {
            "key": key,
            "title": str(raw.get("title") or ""),
            "status": str(raw.get("status") or "ready"),
            "arc": raw.get("arc"),
            "priority": raw.get("priority"),
            "claimed_by": claim.get("by"),
            "claimed_at": claim.get("at"),
            "blocked_on": list(raw.get("blocked_on") or []),
            "defer_reason": raw.get("defer_reason"),
            "related_to": list(raw.get("related_to") or []),
            "artifacts": list(raw.get("artifacts") or []),
            "refs": list(raw.get("refs") or []),
            "tickets": [str(t) for t in (raw.get("tickets") or [])],
            "evidence": raw.get("evidence") or "",
            "evidence_checked_at": raw.get("evidence_checked_at"),
        }
    return by_key


def load_arcs_from_files() -> dict[str, dict[str, Any]]:
    """Parse ``roadmap/arcs/*.yaml``. Same contract as ``load_from_files``:
    raises on the first malformed file, because a half-loaded narrative layer
    renders an ARCS.md that is wrong rather than absent."""
    try:
        import yaml
    except ImportError:  # pragma: no cover
        raise SystemExit("PyYAML required for --source files (pip install pyyaml)") from None
    by_key: dict[str, dict[str, Any]] = {}
    if not ARCS_DIR.is_dir():
        return by_key
    for path in sorted(ARCS_DIR.glob("*.yaml")):
        try:
            raw = yaml.safe_load(path.read_text()) or {}
        except yaml.YAMLError as exc:
            raise SystemExit(f"{path}: invalid YAML: {exc}") from exc
        if not isinstance(raw, dict):
            raise SystemExit(f"{path}: expected a mapping at the top level")
        key = str(raw.get("id") or raw.get("key") or "")
        if key != path.stem:
            raise SystemExit(f"{path}: id {key!r} does not match filename stem {path.stem!r}")
        if not _ID_RE.match(key):
            raise SystemExit(f"{path}: id {key!r} is not kebab-case")
        by_key[key] = {
            "key": key,
            "title": raw.get("title") or "",
            "state": raw.get("state"),
            "state_evidence": raw.get("state_evidence") or "",
            "refs": list(raw.get("refs") or []),
            "narrative": raw.get("narrative") or "",
        }
    return by_key


def load_arcs_from_db() -> dict[str, dict[str, Any]]:
    payload = _api("GET", "/admin/roadmap/arcs") or {}
    return {arc["key"]: arc for arc in payload.get("arcs", [])}


def load_arcs(source: str) -> dict[str, dict[str, Any]]:
    if source == "db":
        return load_arcs_from_db()
    if source == "local":
        return load_arcs_from_local()
    return load_arcs_from_files()


def arc_path(key: str) -> Path:
    return ARCS_DIR / f"{key}.yaml"


def _rel(path: Path) -> str:
    """Repo-relative when it can be, absolute when it cannot.

    ``Path.relative_to`` RAISES for a path outside ``REPO_ROOT``, which makes it
    the wrong call inside an error message: the guard below would crash while
    trying to explain itself, turning a clear refusal into a traceback. In
    production every path here is under the repo; under test they are not.
    """
    try:
        return str(path.relative_to(REPO_ROOT))
    except ValueError:
        return str(path)


def item_path(key: str) -> Path:
    return ITEMS_DIR / f"{key}.yaml"


def _yaml_scalar(value: Any) -> str:
    """Quote only when the plain form would be ambiguous. Keeps hand-authored
    files looking hand-authored instead of machine-mangled."""
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    text = str(value)
    if text == "":
        return '""'
    risky = (
        text[0] in "-?:,[]{}#&*!|>'\"%@`"
        or ": " in text
        # " #" opens a YAML comment mid-scalar: an unquoted `PR #861` loads back
        # as `PR`. A ref silently losing its number is exactly the kind of quiet
        # corruption `pull` must not introduce.
        or " #" in text
        or text[-1] in " :"
    )
    if risky or text.strip() != text or text.lower() in ("null", "true", "false", "~"):
        return "'" + text.replace("'", "''") + "'"
    return text


def _claim_block(claim: dict[str, Any] | None) -> list[str]:
    """The `claim:` block, spelled the same way by every writer.

    Two writers reach here — `claim`'s projection and `pull` — and they used to
    disagree on precision for the *same* claim (seconds vs microseconds), so the
    same fact produced different bytes and the two paths conflicted in git. That
    cost a real merge conflict on #1087. `fmt_timestamp` is the same
    normalisation the renderer applies, so file and render now agree too.

    `at` stays quoted regardless: unquoted, PyYAML resolves an ISO timestamp to
    a datetime, and the file stops round-tripping as the string it was written
    as. Nothing compares `claimed_at` across sources — `diff` and `pull` both
    key on `claimed_by` — so normalising here cannot make either report a
    divergence that is not there.
    """
    if not claim or not claim.get("by"):
        return ["claim: null"]
    at = str(graph.fmt_timestamp(claim.get("at")) or "").replace("'", "''")
    return [
        "claim:",
        f"  by: {_yaml_scalar(claim['by'])}",
        f"  at: '{at}'",
    ]


def _replace_top_level_key(text: str, key: str, new_lines: list[str]) -> str:
    """Swap one top-level block of a YAML item file, leaving every other byte —
    including comments and the ``evidence`` block scalar — untouched.

    A whole-file round-trip through PyYAML would be shorter and would silently
    reformat files other sessions hand-wrote, dropping their comments. A claim is
    a one-field change; it should read as a one-field diff.
    """
    lines = text.splitlines()
    out: list[str] = []
    replaced = False
    i = 0
    while i < len(lines):
        line = lines[i]
        if not replaced and (line == f"{key}:" or line.startswith(f"{key}: ")):
            out.extend(new_lines)
            replaced = True
            i += 1
            # Swallow the old block's continuation lines (indented or list items).
            while i < len(lines) and (
                lines[i].startswith((" ", "\t")) or lines[i].startswith("- ")
            ):
                i += 1
            continue
        out.append(line)
        i += 1
    if not replaced:
        # Insert after the last of the leading identity keys, so the shape stays
        # id → title → status → arc → claim regardless of what the file had.
        anchor = 0
        for idx, line in enumerate(out):
            if line.split(":", 1)[0] in ("id", "title", "status", "arc", "priority"):
                anchor = idx + 1
        out[anchor:anchor] = new_lines
    return "\n".join(out).rstrip() + "\n"


def write_claim_to_file(key: str, claim: dict[str, Any] | None) -> bool:
    """Project a claim into the committed item file. Returns False if there is no
    file to write (a DB-only item — ``pull`` is what fixes that).

    The DB remains the race authority: this runs only *after* the claim
    transaction has already been won or lost. The file is a projection, and it
    exists because a claim otherwise changes no file, so — unlike an item edit —
    it never brings its own commit and no natural moment arrives at which anyone
    syncs it back.
    """
    path = item_path(key)
    if not path.is_file():
        return False
    path.write_text(_replace_top_level_key(path.read_text(), "claim", _claim_block(claim)))
    return True


def render_item_yaml(item: dict[str, Any]) -> str:
    """Emit a full item file, for an item that exists only in the DB."""
    lines = [
        f"id: {_yaml_scalar(item['key'])}",
        f"title: {_yaml_scalar(item.get('title') or '')}",
        f"status: {_yaml_scalar(item.get('status') or 'ready')}",
    ]
    if item.get("arc"):
        lines.append(f"arc: {_yaml_scalar(item['arc'])}")
    # Omitted when unset rather than written as `priority: null`: an absent
    # priority means nobody judged this item, and an explicit null in every file
    # would read as a judgement that was made and came out empty.
    if graph.priority_of(item):
        lines.append(f"priority: {_yaml_scalar(graph.priority_of(item))}")
    lines += _claim_block(
        {"by": item["claimed_by"], "at": item.get("claimed_at")}
        if item.get("claimed_by")
        else None
    )
    deps = list(item.get("blocked_on") or [])
    lines.append("blocked_on: []" if not deps else "blocked_on:")
    lines += [f"- {_yaml_scalar(d)}" for d in deps]
    defer_reason = (item.get("defer_reason") or "").strip()
    if defer_reason:
        lines.append("defer_reason: |")
        lines += [f"  {ln.rstrip()}".rstrip() for ln in defer_reason.splitlines()]
    # Emitted as a block mapping per edge, not inline flow, so a note can be
    # long without the line wrapping into unreadable YAML.
    relations = graph.normalize_relations(item)
    if relations:
        lines.append("related_to:")
        for rel in relations:
            lines.append(f"- key: {_yaml_scalar(rel['key'])}")
            if rel["note"]:
                lines.append(f"  note: {_yaml_scalar(rel['note'])}")
    artifacts = graph.normalize_artifacts(item)
    if artifacts:
        lines.append("artifacts:")
        lines += [f"- {_yaml_scalar(a)}" for a in artifacts]
    refs = list(item.get("refs") or [])
    if refs:
        lines.append("refs:")
        lines += [f"- {_yaml_scalar(r)}" for r in refs]
    # Before the evidence block scalar, like every other list field: anything
    # emitted after `evidence: |` would be swallowed into the prose.
    tickets = [str(t) for t in (item.get("tickets") or [])]
    if tickets:
        lines.append("tickets:")
        lines += [f"- {_yaml_scalar(t)}" for t in tickets]
    evidence = (item.get("evidence") or "").rstrip()
    if evidence:
        lines.append("evidence: |")
        lines += [f"  {ln.rstrip()}".rstrip() for ln in evidence.splitlines()]
    return "\n".join(lines) + "\n"


def _api(method: str, path: str, payload: dict | None = None) -> Any:
    """Call the admin API. Fails loudly with the server's message — a silent
    fallback to stale files would be worse than an error here."""
    token = os.environ.get("LUCILLE_ADMIN_JWT", "").strip()
    if not token:
        raise SystemExit(
            "LUCILLE_ADMIN_JWT is not set — needed for the db source.\n"
            "Mint one with the `mint-admin-jwt` skill, or use --source files."
        )
    base = os.environ.get("LUCILLE_BACKEND_URL", DEFAULT_BACKEND).rstrip("/")
    req = urllib.request.Request(
        f"{base}{path}",
        method=method,
        data=json.dumps(payload).encode() if payload is not None else None,
        headers={
            "Authorization": f"Bearer {token}",
            "Content-Type": "application/json",
        },
    )
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            body = resp.read().decode()
            return json.loads(body) if body else None
    except urllib.error.HTTPError as exc:
        detail = exc.read().decode()[:400]
        raise SystemExit(f"{method} {path} -> HTTP {exc.code}: {detail}") from exc
    except urllib.error.URLError as exc:
        raise SystemExit(f"{method} {path} failed: {exc.reason}") from exc


def load_from_db() -> dict[str, dict[str, Any]]:
    data = _api("GET", "/admin/roadmap") or {}
    return {item["key"]: item for item in data.get("items", [])}


def load_pruned_keys(source: str = "db") -> frozenset[str]:
    """Keys a ``prune`` has spent. Empty rather than fatal when the store cannot
    answer: every caller uses this to SOFTEN a report, so failing closed here
    would turn an unreachable backend into a wall of false drift."""
    if source == "local":
        try:
            with store_for("local") as local:
                return local.pruned_keys()
        except SystemExit:
            return frozenset()
    try:
        data = _api("GET", "/admin/roadmap/prunes") or {}
    except SystemExit:
        return frozenset()
    return frozenset(p["key"] for p in data.get("prunes", []))


def load_from_local() -> dict[str, dict[str, Any]]:
    with store_for("local") as local:
        return local.items()


def load_arcs_from_local() -> dict[str, dict[str, Any]]:
    with store_for("local") as local:
        return local.arcs()


def load(source: str) -> dict[str, dict[str, Any]]:
    if source == "db":
        return load_from_db()
    if source == "local":
        return load_from_local()
    return load_from_files()


# --- commands ----------------------------------------------------------------


def cmd_sync(args: argparse.Namespace) -> int:
    """Regenerate the committed markdown from the chosen source."""
    by_key = load(args.source)
    arcs = load_arcs(args.source)
    rendered = graph.render_markdown(by_key)
    rendered_arcs = graph.render_arcs_markdown(arcs, by_key)
    if args.check:
        current = GENERATED_MD.read_text() if GENERATED_MD.exists() else ""
        current_arcs = GENERATED_ARCS_MD.read_text() if GENERATED_ARCS_MD.exists() else ""
        if current_arcs != rendered_arcs:
            print(
                f"{GENERATED_ARCS_MD.relative_to(REPO_ROOT)} is stale — "
                f"run `{graph.CLI} sync`",
                file=sys.stderr,
            )
            return 1
        # Compared byte-for-byte. There is deliberately nothing to strip: the
        # render carries no clock reading and no graph-wide total, so both
        # sources produce the same bytes and two branches merge cleanly. See
        # `graph.render_markdown`'s docstring for why that is a hard rule.
        if current != rendered:
            print(
                f"{GENERATED_MD.relative_to(REPO_ROOT)} is stale — "
                f"run `{graph.CLI} sync`",
                file=sys.stderr,
            )
            return 1
        print("ROADMAP.md and ARCS.md are up to date")
        return 0
    # REFUSE TO WIPE THE NARRATIVE LAYER. `sync --source db` renders arcs from
    # /admin/roadmap/arcs, which does not exist until the backend carrying it is
    # deployed — and roadmap-sync.yml runs on the merge commit, minutes ahead of
    # that deploy. A missing endpoint makes `_api` exit loudly, which is right,
    # but an endpoint that answers with an empty list would render a valid
    # ARCS.md with every arc silently deleted and commit it to main. Cheap
    # guard, and the failure it prevents is unrecoverable from the artifact
    # itself.
    if not arcs and load_arcs_from_files():
        print(
            f"refusing to write {_rel(GENERATED_ARCS_MD)}: source="
            f"{args.source} returned 0 arcs but roadmap/arcs/ has "
            f"{len(load_arcs_from_files())}. If the store is genuinely empty, "
            f"seed it with `roadmap.py push` first.",
            file=sys.stderr,
        )
        return 1
    GENERATED_MD.parent.mkdir(parents=True, exist_ok=True)
    GENERATED_MD.write_text(rendered)
    GENERATED_ARCS_MD.write_text(rendered_arcs)
    print(
        f"wrote {GENERATED_MD.relative_to(REPO_ROOT)} "
        f"({len(by_key)} item(s), source={args.source})"
    )
    print(
        f"wrote {GENERATED_ARCS_MD.relative_to(REPO_ROOT)} "
        f"({len(arcs)} arc(s), source={args.source})"
    )
    return 0


def status_divergences(
    db: dict[str, dict[str, Any]], files: dict[str, dict[str, Any]]
) -> list[str]:
    """Where a file's status says something the store, which owns it, does not.

    Compared on ``done``-ness alone, for the same reason ``compare_sources``
    does: every other status is re-derived from the edges, so a raw comparison
    would cry wolf on every item whose dependency moved.

    Pure, so it is testable without a DB.
    """
    lines: list[str] = []
    for key in sorted(set(db) & set(files)):
        d, f = db[key].get("status"), files[key].get("status")
        if (d == "done") == (f == "done"):
            continue
        if f == "done":
            lines.append(
                f"{key}: the file says done, the store says {d!r} — if the file is "
                f"right, run `roadmap.py status {key} done`"
            )
        else:
            lines.append(
                f"{key}: the store says done, the file says {f!r} — the store wins. "
                f"If this file predates a `prune`, run `roadmap.py pull`"
            )
    return lines


def cmd_push(args: argparse.Namespace) -> int:
    """Upload the YAML seed files into the DB.

    Prose, edges and refs only: ``status`` and the claim belong to the store and
    are ignored for an item that already exists (``crud/roadmap.upsert_item``).
    That asymmetry is why this command is safe to run from a slightly stale
    checkout — on 2026-08-02 it was not, and a push from a checkout predating a
    ``prune`` resurrected finished work as ``ready``, silently un-starting every
    item that depended on it.

    Status still has to be *sayable*, so a push reports where the file and the
    store disagree about ``done`` and names the command that resolves it. The
    push is not failed by a divergence — the item bodies are still worth
    uploading, and a divergence is a decision for the operator, not an error.
    """
    by_key = load_from_files()
    if not by_key:
        print("no item files to push")
        return 0
    stores = _stores()
    local = store_for("local") if _write_source(args) == "local" else None
    resurrected: list[str] = []
    for key in sorted(by_key):
        item = by_key[key]
        payload = {
            "key": key,
            "title": item["title"],
            "status": item["status"],
            "arc": item["arc"],
            "priority": item["priority"],
            "blocked_on": item["blocked_on"],
            "defer_reason": item["defer_reason"],
            "related_to": item["related_to"],
            "artifacts": item["artifacts"],
            "refs": item["refs"],
            "tickets": item.get("tickets") or [],
            "evidence": item["evidence"],
        }
        try:
            if local is not None:
                local.upsert_item(payload)
            else:
                _api("PUT", f"/admin/roadmap/{key}", payload)
        except stores.Pruned:
            # Same outcome as the API's 409, reached by the same reasoning — see
            # below. Two exception types because one store answers over HTTP and
            # the other raises in-process; one meaning.
            resurrected.append(key)
            continue
        except SystemExit as exc:
            if not _is_pruned_conflict(exc):
                raise
            # SKIPPED, NOT FAILED. This is the ordinary state of the world for
            # the ~27 hours between a prune and its PR merging: `main` still
            # carries the files, the hourly sync pushes them, and every one of
            # them is a key the store has deliberately spent. Failing the run
            # here would turn a correct refusal into an hourly red build and
            # teach everyone to ignore it.
            resurrected.append(key)
            continue
        print(f"pushed {key}")
    arcs = load_arcs_from_files()
    for key in sorted(arcs):
        arc = arcs[key]
        arc_payload = {
            "title": arc["title"],
            "state": arc["state"],
            "state_evidence": arc["state_evidence"],
            "refs": arc["refs"],
            "narrative": arc["narrative"],
        }
        if local is not None:
            local.upsert_arc(dict(arc_payload, key=key))
        else:
            _api("PUT", f"/admin/roadmap/arcs/{key}", arc_payload)
        print(f"pushed arc {key}")
    print(f"{len(by_key) - len(resurrected)} item(s), {len(arcs)} arc(s) pushed")
    if resurrected:
        # Named, not counted. The whole failure this guards against was silent,
        # so the one thing the fix must not be is quiet about what it stopped.
        print(
            f"\n{len(resurrected)} file(s) name a key that was PRUNED; the store "
            f"refused to recreate them:",
            file=sys.stderr,
        )
        for key in resurrected:
            print(f"  {key}", file=sys.stderr)
        print(
            "  These files are stale — they are still on `main` because the "
            "prune's PR has not merged yet.\n"
            "  Nothing to do if that PR is open. If a key is genuinely being "
            "refiled, run `roadmap.py refile <key>`.",
            file=sys.stderr,
        )
    # Best-effort: the push already landed, and a failed read here must not turn
    # a successful push into a non-zero exit.
    try:
        divergences = status_divergences(
            local.items() if local is not None else load_from_db(), by_key
        )
    except Exception:  # noqa: BLE001 - a nudge is never worth failing the push
        return 0
    finally:
        if local is not None:
            local.close()
    if divergences:
        print(
            "\nstatus is owned by the store and was NOT changed by this push:",
            file=sys.stderr,
        )
        for line in divergences:
            print(f"  {line}", file=sys.stderr)
    return 0


def cmd_status(args: argparse.Namespace) -> int:
    """Move one item's status deliberately — the only writer for that field.

    Separate from ``push`` on purpose: a status is a statement about the work,
    not a property of whichever checkout ran the upload last.
    """
    if _write_source(args) == "local":
        with store_for("local") as store:
            store.set_status(args.key, args.status)
    else:
        _api("POST", f"/admin/roadmap/{args.key}/status", {"status": args.status})
    print(f"{args.key} is now {args.status}")
    path = item_path(args.key)
    if path.exists():
        with switchboard_write_lock(args.key):
            path.write_text(
                _replace_top_level_key(path.read_text(), "status", [f"status: {args.status}"])
            )
        print(f"projected into roadmap/items/{args.key}.yaml — run `sync`, then commit it")
    else:
        print(
            f"warning: no roadmap/items/{args.key}.yaml to project into. "
            f"Run `roadmap.py pull` first.",
            file=sys.stderr,
        )
    if args.status == "done":
        print("done also drops the claim — `roadmap.py prune` when you are ready to clear it")
        # No lease to drop here any more. This used to release the long-lived
        # mirror, which the store's `done` side effect would otherwise leave
        # reading as "claimed and alive" for up to four hours after the roadmap
        # side had let go. A write lock is already released by the time the
        # write returns, so there is nothing left holding.
    if args.status == "verifying":
        print(
            "verifying does NOT drop the claim — the branch that shipped this still "
            "owns confirming it. Move to `done` once the effect is actually observed "
            "(e.g. its post-merge check reports), not when the code merges."
        )
    return 0


def compare_sources(
    db: dict[str, dict[str, Any]], files: dict[str, dict[str, Any]],
    pruned: set[str] | frozenset[str] = frozenset(),
) -> list[str]:
    """Every way the store and the committed files disagree that a session would
    act on. Pure, so it is testable without a DB.

    Deliberately NOT compared: ``evidence`` and ``refs``. Those churn on every
    edit and a prose difference is not something another session collides on.
    What is compared is what changes a decision — does this item exist, is it
    finished, who holds it, what is it waiting for.

    ``pruned`` IS NOT AN EXEMPTION LIST, it is the difference between a
    divergence and a state. A key with a tombstone is *supposed* to be in the
    files and absent from the store for as long as the prune's PR is open —
    that gap is the prune working, and the store refusing to recreate it is the
    guard working. Before the tombstone existed the gap closed by itself
    because ``push`` resurrected the item, which is precisely the bug; so
    fixing that bug turns a self-healing divergence into a persistent one, and
    an hourly ``diff`` that fails on it would fail every hour for a day and be
    read as noise. Reported separately by ``cmd_diff`` rather than silently.
    """
    problems: list[str] = []
    for key in sorted(set(db) - set(files)):
        problems.append(
            f"{key}: in the DB but NOT in roadmap/items/ — invisible to any agent "
            f"in a checkout. Fix: `roadmap.py pull`"
        )
    for key in sorted(set(files) - set(db) - set(pruned)):
        problems.append(
            f"{key}: in roadmap/items/ but NOT in the DB — `claim` would 404 and "
            f"`--source db` cannot see it. Fix: `roadmap.py push`"
        )
    for key in sorted(set(db) & set(files)):
        d, f = db[key], files[key]
        if (d.get("status") == "done") != (f.get("status") == "done"):
            finished, stale = ("files", "DB") if f.get("status") == "done" else ("DB", "files")
            problems.append(
                f"{key}: done in the {finished} but not in the {stale} — `done` is the "
                f"one status the graph cannot derive, so the {stale} will keep offering "
                f"finished work as startable"
            )
        if (d.get("claimed_by") or None) != (f.get("claimed_by") or None):
            problems.append(
                f"{key}: claim differs — DB={d.get('claimed_by') or 'none'!r}, "
                f"files={f.get('claimed_by') or 'none'!r}"
            )
        if list(d.get("blocked_on") or []) != list(f.get("blocked_on") or []):
            problems.append(
                f"{key}: blocked_on differs — DB={list(d.get('blocked_on') or [])}, "
                f"files={list(f.get('blocked_on') or [])}"
            )
        # Compared for the same reason as blocked_on: it decides whether the
        # item is offered as startable, so a divergence here means the two
        # sources hand different work to the next session.
        # Presence only, not wording: whether the item is deferred decides what
        # the two sources offer as startable, and that is what another session
        # collides on. The prose churns like evidence does and comparing it
        # would cry wolf on every reword.
        if bool((d.get("defer_reason") or "").strip()) != bool(
            (f.get("defer_reason") or "").strip()
        ):
            deferred_in = "DB" if (d.get("defer_reason") or "").strip() else "files"
            offered_in = "files" if deferred_in == "DB" else "DB"
            problems.append(
                f"{key}: defer_reason differs — deferred in the {deferred_in}, still "
                f"offered as startable by the {offered_in}"
            )
        # Compared for the same reason as blocked_on and defer_reason: it
        # decides what the two sources hand the next session FIRST. A priority
        # that landed in one source only is an ordering somebody stated and the
        # other half of the system never heard — which is the state this field
        # was added to end, so it must not be reintroduced as drift.
        if graph.priority_of(d) != graph.priority_of(f):
            problems.append(
                f"{key}: priority differs — DB={graph.priority_of(d) or 'unset'!r}, "
                f"files={graph.priority_of(f) or 'unset'!r}"
            )
        # Compared like blocked_on: it is an edge, and an edge that landed in
        # one source only is a warning the other half of the system never
        # gives. Keys only, not notes — the note churns like evidence does and
        # comparing it would cry wolf on every reword, while a missing *pair*
        # is what actually costs a session a rebase.
        d_rel = [r["key"] for r in graph.normalize_relations(d)]
        f_rel = [r["key"] for r in graph.normalize_relations(f)]
        if d_rel != f_rel:
            problems.append(
                f"{key}: related_to differs — DB={d_rel}, files={f_rel}"
            )
        # Same reason as related_to, one step weaker: a missing artifact
        # declaration is a missing WARNING, not a missing edge. Nobody is
        # blocked by it — they just find out at merge time, which is the state
        # the field was added to end.
        d_art = graph.normalize_artifacts(d)
        f_art = graph.normalize_artifacts(f)
        if d_art != f_art:
            problems.append(f"{key}: artifacts differ — DB={d_art}, files={f_art}")
        if (d.get("title") or "") != (f.get("title") or ""):
            problems.append(f"{key}: title differs between the DB and the files")
    return problems


def cmd_diff(args: argparse.Namespace) -> int:
    """Report where the store and the committed files disagree.

    Neither existing guard can see this axis. ``validate`` checks one source in
    isolation; ``sync --check`` compares ROADMAP.md against items/*.yaml, and
    both of those are committed, so they agree with each other while both
    disagree with the DB. That is exactly how three items lived in the store
    invisible to every checkout.
    """
    source = getattr(args, "source", "db")
    db, files = load(source), load_from_files()
    pruned = load_pruned_keys(source)
    awaiting_merge = sorted((set(files) & pruned) - set(db))
    problems = compare_sources(db, files, pruned)
    # Arcs too, or the arc layer drifts exactly the way the item layer used to:
    # `pull` creates a missing arc file but never updates an existing one, so a
    # state declared against the store reaches no checkout and nothing says so.
    problems += graph.compare_arc_sources(load_arcs(source), load_arcs_from_files())
    if awaiting_merge:
        # Said out loud, and NOT counted as drift. This is the normal state
        # between a prune and its PR merging, and an operator who does not know
        # that will read a silent difference as the store having lost something.
        print(
            f"{len(awaiting_merge)} pruned item(s) still have a file on this "
            f"checkout — normal until the prune's PR merges:"
        )
        for key in awaiting_merge:
            print(f"  {key}")
    if not problems:
        print("db and files agree")
        return 0
    for problem in problems:
        print(f"drift: {problem}", file=sys.stderr)
    print(f"\n{len(problems)} divergence(s)", file=sys.stderr)
    return 1


def cmd_pull(args: argparse.Namespace) -> int:
    """The inverse of ``push``: bring the store's reality back into the checkout.

    Creates a file for every DB-only item and projects live claims and ``done``
    onto the items that already have one. It does NOT rewrite existing evidence
    or refs — those are hand-authored and the DB copy is usually the older one.
    """
    source = getattr(args, "source", "db")
    db = load(source)
    files = load_from_files()
    created, updated = [], []
    ITEMS_DIR.mkdir(parents=True, exist_ok=True)
    for key in sorted(db):
        item = db[key]
        if key not in files:
            item_path(key).write_text(render_item_yaml(item))
            created.append(key)
            continue
        local = files[key]
        changed = False
        if (item.get("claimed_by") or None) != (local.get("claimed_by") or None):
            claim = (
                {"by": item["claimed_by"], "at": item.get("claimed_at")}
                if item.get("claimed_by")
                else None
            )
            changed = write_claim_to_file(key, claim) or changed
        if item.get("status") == "done" and local.get("status") != "done":
            path = item_path(key)
            path.write_text(
                _replace_top_level_key(path.read_text(), "status", ["status: done"])
            )
            changed = True
        # A priority set straight against the API (by an operator with no
        # checkout — the case that motivated the field) changes no file, so
        # without this it stays invisible to every agent reading the backlog,
        # which is the failure mode a claim already had before it was projected.
        if graph.priority_of(item) != graph.priority_of(local):
            path = item_path(key)
            block = (
                [f"priority: {_yaml_scalar(graph.priority_of(item))}"]
                if graph.priority_of(item)
                else []
            )
            path.write_text(_replace_top_level_key(path.read_text(), "priority", block))
            changed = True
        if changed:
            updated.append(key)
    # Arcs, same direction and same reason: an arc that exists only in the store
    # is invisible to every agent reading a checkout, which is the whole failure
    # `pull` exists to heal. Written wholesale rather than key-by-key because an
    # arc has no store-owned field to protect — no claim, no status transition —
    # so the store's copy IS the authored form.
    arcs_created: list[str] = []
    db_arcs = load_arcs(source)
    ARCS_DIR.mkdir(parents=True, exist_ok=True)
    for key in sorted(db_arcs):
        path = arc_path(key)
        if path.exists():
            continue
        arc = db_arcs[key]
        out = [f"id: {key}", f"title: {_yaml_scalar(arc.get('title') or '')}"]
        if arc.get("state"):
            out.append(f"state: {arc['state']}")
            out.append("state_evidence: |")
            out.extend(
                f"  {line}" if line.strip() else ""
                for line in (arc.get("state_evidence") or "").splitlines()
            )
        refs = list(arc.get("refs") or [])
        out.append("refs:" if refs else "refs: []")
        out.extend(f"- {_yaml_scalar(str(r))}" for r in refs)
        out.append("narrative: |")
        out.extend(
            f"  {line}" if line.strip() else ""
            for line in (arc.get("narrative") or "").splitlines()
        )
        path.write_text("\n".join(out) + "\n")
        arcs_created.append(key)

    for key in created:
        print(f"created roadmap/items/{key}.yaml")
    for key in updated:
        print(f"updated roadmap/items/{key}.yaml")
    for key in arcs_created:
        print(f"created roadmap/arcs/{key}.yaml")
    if not created and not updated and not arcs_created:
        print("nothing to pull — the files already match the store")
        return 0
    print(
        f"{len(created)} created, {len(updated)} updated — "
        f"now run `{graph.CLI} sync` and commit"
    )
    return 0


def _offline_notice(args: argparse.Namespace) -> None:
    """One line, on stderr, whenever a read is served from the checkout.

    ``claim`` now projects into the item files, but the projection is only as
    fresh as the last commit — a session that claimed something ten minutes ago
    on an unmerged branch is invisible here. Saying so is cheap; discovering it
    by colliding is not.
    """
    if getattr(args, "source", "files") == "files":
        print(
            "note: claims here are the committed projection and can lag the store. "
            "`--source db` is authoritative; `roadmap.py diff` shows the gap.",
            file=sys.stderr,
        )


def _stale_claim_notice(by_key: dict[str, dict[str, Any]]) -> None:
    """Name holds that have outlived a plausible session, on stderr.

    Detection has to live where somebody already looks. A dashboard nobody
    opens, or a scheduled job whose output lands in a queue, both lose to one
    line printed at the moment a session is choosing what to work on — which is
    exactly when a dead hold is doing its damage, by hiding a startable item.
    """
    stale = graph.stale_claims(by_key)
    if not stale:
        return
    print(
        f"\nnote: {len(stale)} claim(s) held longer than {graph.STALE_CLAIM_DAYS}d — "
        f"likely finished sessions that never released:",
        file=sys.stderr,
    )
    for item in stale:
        print(
            f"  {item['key']} — {item.get('claimed_by')} "
            f"({item['claim_age_days']:.1f}d ago)",
            file=sys.stderr,
        )
    print(
        "  Verify the branch is merged or gone, then `roadmap.py release <key>`.",
        file=sys.stderr,
    )


def _own_claims_notice(by_key: dict[str, dict[str, Any]], *, exclude: str = "") -> None:
    """Remind THIS branch of what it is still holding.

    The nudge that actually has a chance of working: it reaches the one session
    that knows whether the work is done, while it is still running. Every other
    mechanism here is archaeology performed after that session is gone.
    """
    branch = current_branch()
    if branch == "unknown":
        return
    held = [
        key
        for key, item in sorted(by_key.items())
        if item.get("claimed_by") == branch and key != exclude
    ]
    if not held:
        return
    print(
        f"\nnote: your branch ({branch}) still holds {', '.join(held)}. "
        "Release what you are done with — `roadmap.py release <key>` — so it goes "
        "back on the queue; an unreleased claim outlives this session silently.",
        file=sys.stderr,
    )


def _git(*args: str) -> tuple[int, str]:
    """Run git, returning (rc, stdout). Never raises — a checkout with no git
    is a case the caller decides about, not one this helper dies on."""
    try:
        proc = subprocess.run(
            ["git", *args], capture_output=True, text=True, timeout=30,
            cwd=str(REPO_ROOT),
        )
    except (OSError, subprocess.SubprocessError) as exc:  # noqa: BLE001
        return 1, str(exc)
    return proc.returncode, proc.stdout.strip()


def prune_staleness_blockers() -> list[str]:
    """Why this checkout must not run a prune. Empty means it may.

    THE PRECONDITION FOR THE WHOLE BUG. A prune deletes from the store
    immediately and from `main` only when its PR merges; in between, the hourly
    sync pushes the still-present files back. The tombstone above makes that
    resurrection impossible, but it does not make pruning from a stale checkout
    a good idea: the item set you are pruning is the one your files describe,
    and if those files disagree with `main` you are deciding about work you
    cannot see.

    REFUSING RATHER THAN WARNING, deliberately. A warning on a destructive
    command that is correct most of the time gets learned as noise, and this
    command is run rarely enough that being stopped once costs a `git pull`.

    Checks, and what each one catches:
      * uncommitted changes under roadmap/items/ — a local edit that no review
        has seen would be pruned or preserved on its own say-so.
      * roadmap/items/ differing from origin/main — the actual 2026-08-15
        precondition. The first prune ran from a branch whose deletions were
        not on main.
    A fetch is attempted so "matches origin/main" is a statement about the real
    origin/main and not a stale ref; if it fails, that is reported rather than
    silently compared against whatever was last fetched.
    """
    blockers: list[str] = []
    rc, out = _git("status", "--porcelain", "--", "roadmap/items")
    if rc != 0:
        return [f"could not read git status ({out or 'git failed'})"]
    if out:
        # `[2:]` then strip, not `[3:]`: porcelain is `XY<space>PATH`, but the
        # whole output has already been stripped, so the leading space of an
        # unstaged ` M path` is gone and a fixed offset of 3 eats the first
        # character of the filename. Cutting the two status columns and
        # stripping whatever separator survives is right either way.
        names = ", ".join(
            sorted({line[2:].strip() for line in out.splitlines() if line.strip()})[:5]
        )
        blockers.append(f"uncommitted changes under roadmap/items/: {names}")
    fetch_rc, fetch_out = _git("fetch", "origin", "main", "--quiet")
    if fetch_rc != 0:
        blockers.append(
            f"could not fetch origin/main, so 'matches main' is unverifiable "
            f"({fetch_out or 'fetch failed'})"
        )
        return blockers
    rc, out = _git("diff", "--name-only", "origin/main", "--", "roadmap/items")
    if rc != 0:
        return blockers + [f"could not diff against origin/main ({out or 'git failed'})"]
    if out:
        files = out.splitlines()
        shown = ", ".join(sorted(files)[:5])
        more = f" (+{len(files) - 5} more)" if len(files) > 5 else ""
        blockers.append(f"roadmap/items/ differs from origin/main: {shown}{more}")
    return blockers


def _is_pruned_conflict(exc: BaseException) -> bool:
    """Was this the store refusing to resurrect a pruned key?

    Matched on the status line `_api` builds rather than anywhere in the
    message: a detail body can contain any three digits, and an item key or a
    piece of evidence prose containing "409" must not be read as a conflict.
    """
    return "-> HTTP 409:" in str(exc)


def cmd_refile(args: argparse.Namespace) -> int:
    """Let a pruned key be filed again.

    The escape hatch the push refusal names. Deliberately a separate command
    rather than a flag on `push`: a flag would be reached for whenever a push
    complained, which is every hourly sync between a prune and its merge, and
    the guard would be off within a week.
    """
    _api("POST", f"/admin/roadmap/{args.key}/refile")
    print(
        f"{args.key} may be filed again — its prune tombstone is cleared.\n"
        f"Write roadmap/items/{args.key}.yaml and `push`."
    )
    return 0


def _api_delete_tolerant(key: str) -> str:
    """DELETE one item, treating 404 as success. Already-gone is the outcome we
    want, and failing on it would make a half-finished prune unrepeatable."""
    try:
        _api("DELETE", f"/admin/roadmap/{key}")
        return "deleted"
    except SystemExit as exc:
        if "404" in str(exc):
            return "already absent"
        raise


def cmd_prune(args: argparse.Namespace) -> int:
    """Delete every ``done`` item from BOTH the store and the checkout.

    ``roadmap/README.md`` rule 4 — "delete when done, do not accumulate a done
    pile" — and the DELETE endpoint that implements it have both existed since
    the store landed, with nothing wiring them together. So the rule was only
    followable by hand-writing an API call, which meant it was not followed: five
    done items had piled up by 2026-08-01.

    The evidence is not lost by this. It lives in git history, and anything worth
    carrying forward should already be in ``ARCS.md`` or the design doc — an item
    is a work ticket, not an archive.

    DB first, then the file: if the store delete fails the file stays, so a
    partial run is simply re-runnable rather than leaving an item that exists in
    a checkout and nowhere else.

    REFUSES FROM A STALE CHECKOUT (``prune_staleness_blockers``). The item set
    being pruned is the one this checkout's files describe; if they disagree
    with ``origin/main`` the decision is being made about work the operator
    cannot see.
    """
    blockers = prune_staleness_blockers()
    if blockers and not args.allow_stale:
        print("refusing to prune from this checkout:", file=sys.stderr)
        for line in blockers:
            print(f"  {line}", file=sys.stderr)
        print(
            "\n`prune` decides which items stop existing, using this checkout's "
            "files as the list.\nA checkout that disagrees with `origin/main` is "
            "deciding about work it cannot see.\n"
            "Fix with `git fetch origin main && git rebase origin/main`, or pass "
            "--allow-stale if\nyou have read the difference and it is deliberate.",
            file=sys.stderr,
        )
        return 2
    if blockers:
        print("proceeding with --allow-stale despite:", file=sys.stderr)
        for line in blockers:
            print(f"  {line}", file=sys.stderr)
    files = load_from_files()
    done = sorted(k for k, i in files.items() if i.get("status") == "done")
    try:
        done += sorted(
            k for k, i in load_from_db().items() if i.get("status") == "done" and k not in done
        )
    except SystemExit as exc:  # no JWT / API down — the file side still prunes
        print(f"warning: could not read the store ({exc}); pruning files only", file=sys.stderr)
    if not done:
        print("no done items — nothing to prune")
        return 0
    # A pruned item takes its `done_at`, `done_version` and ticket links with it,
    # and those are exactly the fields `impact` reads — the answer to "is anybody
    # still complaining about this after we fixed it" only exists while the item
    # does. Warned, not blocked: rule 4 says do not accumulate a done pile, and
    # silently refusing to prune would rebuild the pile this command exists to
    # clear. Run `impact` first if the answer still matters.
    linked = {k: files.get(k, {}).get("tickets") or [] for k in done}
    linked = {k: v for k, v in linked.items() if v}
    if linked:
        print(
            "warning: these carry ticket links; `impact` cannot answer for them "
            "once pruned:",
            file=sys.stderr,
        )
        for key, ids in sorted(linked.items()):
            print(f"  {key}  ({len(ids)} ticket(s))", file=sys.stderr)

    if not args.yes:
        print("would prune (re-run with --yes):")
        for key in done:
            print(f"  {key}  {files.get(key, {}).get('title', '(db only)')}")
        return 0
    for key in done:
        outcome = _api_delete_tolerant(key)
        path = item_path(key)
        if path.exists():
            path.unlink()
            print(f"pruned {key} — store: {outcome}, file removed")
        else:
            print(f"pruned {key} — store: {outcome}, no file")
    _release_dependents(done)
    print(f"{len(done)} item(s) pruned — now run `{graph.CLI} sync` and commit")
    return 0


def _release_dependents(pruned: list[str]) -> None:
    """Drop edges pointing at a pruned item from everything that depended on it.

    Deleting a ``done`` item without this INVERTS the meaning of every edge into
    it. ``unmet_deps`` counts a dangling dependency as unmet — deliberately, since
    pointing at something that does not exist is not the same as satisfied — so
    the dependent silently becomes permanently ``blocked`` and unstartable. That
    is strictly worse than the done pile the prune exists to clear.

    A satisfied edge is what is being removed here, not a real one: the
    dependency was ``done``, which is precisely why it is being pruned. Removing
    the edge preserves the graph's meaning; leaving it dangling destroys it.

    ``related_to`` is swept the same way, for a weaker but real reason: a
    relation cannot block anything, so a dangling one costs nobody a startable
    item — but ``validate_graph`` reports it as an unknown-item problem, and
    ROADMAP.md renders graph problems above everything else. A prune that leaves
    a permanent warning on the artifact trains readers to ignore the warnings.
    """
    gone = set(pruned)
    # RECONCILED AGAINST THE STORE, not against whether the local file changed.
    # It is the store's edges this repairs, and the two questions come apart
    # exactly when it matters: run against an already-corrected checkout,
    # nothing in the files changes, so the old version skipped every item and
    # left the store holding `blocked_on` edges to items that no longer exist.
    # That is the permanently-blocked condition this function exists to prevent,
    # left in place by the function that prevents it — measured 2026-08-16, six
    # divergences reported by `diff` right after a successful prune.
    #
    # Best-effort: a store that cannot be read is already reported by the prune
    # above, and the file-side correction below is still worth making.
    try:
        stored = load_from_db()
    except SystemExit as exc:
        print(f"  warning: could not read the store ({exc}); "
              f"correcting files only", file=sys.stderr)
        stored = {}
    for key, item in sorted(load_from_files().items()):
        remaining = [d for d in (item.get("blocked_on") or []) if d not in gone]
        relations = graph.normalize_relations(item)
        kept_rel = [r for r in relations if r["key"] not in gone]
        deps_changed = remaining != list(item.get("blocked_on") or [])
        rels_changed = kept_rel != relations
        db_item = stored.get(key)
        db_stale = db_item is not None and bool(
            [d for d in (db_item.get("blocked_on") or []) if d in gone]
            or [r for r in graph.normalize_relations(db_item) if r["key"] in gone]
        )
        if not deps_changed and not rels_changed and not db_stale:
            continue
        path = item_path(key)
        if deps_changed:
            block = (
                ["blocked_on: []"]
                if not remaining
                else ["blocked_on:"] + [f"- {_yaml_scalar(d)}" for d in remaining]
            )
            path.write_text(_replace_top_level_key(path.read_text(), "blocked_on", block))
            dropped = sorted(set(item.get("blocked_on") or []) & gone)
            print(f"  {key}: dropped satisfied dep(s) {', '.join(dropped)}")
        if rels_changed:
            block: list[str] = []
            for rel in kept_rel:
                block.append(f"- key: {_yaml_scalar(rel['key'])}")
                if rel["note"]:
                    block.append(f"  note: {_yaml_scalar(rel['note'])}")
            block = ["related_to:"] + block if block else ["related_to: []"]
            path.write_text(_replace_top_level_key(path.read_text(), "related_to", block))
            dropped_rel = sorted({r["key"] for r in relations} & gone)
            print(f"  {key}: dropped relation(s) to pruned item(s) {', '.join(dropped_rel)}")
        if not deps_changed and not rels_changed:
            # Reached only via `db_stale`: the file is already correct and the
            # store is not. Said out loud because this is the case the old
            # version silently skipped, and a repair nobody can see is the
            # thing this whole item is about.
            print(f"  {key}: file already correct, repairing the store's edges")
        try:
            fresh = load_from_files()[key]
            # Every authored field goes up, not just the edge that changed: this
            # is a full PUT, so a field omitted here is a field CLEARED in the
            # store. `defer_reason` was already being dropped that way — a prune
            # silently un-deferred any item that depended on a pruned one — and
            # `priority` would have joined it.
            _api("PUT", f"/admin/roadmap/{key}", {
                "key": key, "title": fresh["title"], "status": fresh["status"],
                "arc": fresh["arc"], "priority": fresh["priority"],
                "blocked_on": fresh["blocked_on"],
                "defer_reason": fresh["defer_reason"],
                "related_to": fresh["related_to"],
                "artifacts": fresh["artifacts"],
                "refs": fresh["refs"], "tickets": fresh.get("tickets") or [],
                "evidence": fresh["evidence"],
            })
        except SystemExit as exc:
            print(f"  warning: {key} edge dropped in files but not the store ({exc})",
                  file=sys.stderr)


def cmd_list(args: argparse.Namespace) -> int:
    by_key = load(args.source)
    if not by_key:
        print("no items")
        return 0
    _offline_notice(args)
    if args.json:
        # The two sources disagree on type for a timestamp — PyYAML resolves it
        # to a datetime, the API returns a string — so `--json --source files`
        # used to die on "Object of type datetime is not JSON serializable"
        # while `--source db` worked. Same root cause as the render drift
        # fmt_timestamp fixes; normalise here too so the two sources emit the
        # same JSON, with default=str as a backstop that keeps any future
        # non-serialisable field from taking the command out entirely.
        for item in by_key.values():
            for field in ("claimed_at", "evidence_checked_at"):
                if item.get(field) is not None:
                    item[field] = graph.fmt_timestamp(item[field])
        print(json.dumps(by_key, indent=2, default=str, sort_keys=True))
        return 0
    for statename in graph.STATUSES:
        # Within a status band, the same priority-then-key order the queue hands
        # work out in. A `list` that disagreed with `ready` about which item
        # comes first would be a second ordering for a reader to reconcile.
        group = sorted(
            (i for i in by_key.values() if graph.derive_status(i, by_key) == statename),
            key=graph.queue_sort_key,
        )
        if not group:
            continue
        print(f"\n{statename.upper()} ({len(group)})")
        for item in group:
            suffix = ""
            if item.get("claimed_by"):
                suffix = f"  [{item['claimed_by']}]"
                age = graph.claim_age_days(item)
                if age is not None and age >= graph.STALE_CLAIM_DAYS:
                    suffix += f"  ⚠️ held {age:.1f}d"
            elif unmet := graph.unmet_deps(item, by_key):
                suffix = f"  ← {', '.join(unmet)}"
            print(
                f"  {graph.priority_of(item) or '':<6} "
                f"{item['key']:<38} {item['title']}{suffix}"
            )
    _stale_claim_notice(by_key)
    return 0


def cmd_ready(args: argparse.Namespace) -> int:
    by_key = load(args.source)
    ready = graph.ready_items(by_key)
    if not ready:
        print("nothing ready — everything is claimed, blocked, or done")
        return 0
    _offline_notice(args)
    # Priority first, then key — the same order `ROADMAP.md` and the API use, so
    # "the first one" means one thing whichever surface a session read it from.
    # Blank column for an unjudged item, so a stated priority is visible at a
    # glance and absence never reads as a grade.
    for item in ready:
        print(f"{graph.priority_of(item) or '':<6} {item['key']:<38} {item['title']}")
        # The reason this edge exists. A relation printed only by `show` would
        # be read after the claim, and the ten pairs this replaced were all
        # already written down somewhere a claiming session did not look.
        for rel in graph.relations_for(item["key"], by_key):
            note = f" — {rel['note']}" if rel["note"] else ""
            print(f"{'':<6} ↔ related: {rel['key']}{note}")
        # Printed against the item, not as a footer, so it is read by whoever
        # is looking at that line. Still offered — this is a merge cost, not a
        # reason the item is unstartable.
        for clash in graph.artifact_contention(item["key"], by_key):
            print(
                f"{'':<6} ⚠ merge contention on {', '.join(clash['artifacts'])} "
                f"with {clash['key']} [{clash['claimed_by']}]"
            )
    # A session asking what to start is about to add a claim; this is the moment
    # it is most able — and most likely — to notice one it should drop.
    _own_claims_notice(by_key)
    _stale_claim_notice(by_key)
    return 0


def cmd_show(args: argparse.Namespace) -> int:
    by_key = load(args.source)
    item = by_key.get(args.key)
    if item is None:
        print(f"no such item: {args.key}", file=sys.stderr)
        return 1
    _offline_notice(args)
    print(f"{item['key']}\n{'=' * len(item['key'])}")
    print(f"title:   {item['title']}")
    print(f"status:  {graph.derive_status(item, by_key)}")
    if item.get("arc"):
        print(f"arc:     {item['arc']}")
    if graph.priority_of(item):
        print(f"priority: {graph.priority_of(item)}")
    if item.get("claimed_by"):
        age = graph.claim_age_days(item)
        held = "" if age is None else f" ({age:.1f}d ago)"
        stale = "" if age is None or age < graph.STALE_CLAIM_DAYS else "  ⚠️ likely stale"
        print(f"claimed: {item['claimed_by']} at {item.get('claimed_at')}{held}{stale}")
    if (item.get("defer_reason") or "").strip():
        print(f"deferred: {' '.join(item['defer_reason'].split())}")
    for dep in item.get("blocked_on") or []:
        mark = "done" if by_key.get(dep, {}).get("status") == "done" else "OPEN"
        title = by_key[dep]["title"] if dep in by_key else "??? unknown item"
        print(f"blocked_on: [{mark}] {dep} — {title}")
    for other_key, other in sorted(by_key.items()):
        if item["key"] in (other.get("blocked_on") or []):
            print(f"blocks:  {other_key}")
    # Both directions, and printed above refs because it is the line that
    # changes whether this item should be started at all right now.
    for rel in graph.relations_for(item["key"], by_key):
        note = f" — {rel['note']}" if rel["note"] else ""
        unknown = "" if rel["key"] in by_key else "  ??? unknown item"
        print(f"related: {rel['key']}{note}{unknown}")
    artifacts = graph.normalize_artifacts(item)
    if artifacts:
        print(f"artifacts: {', '.join(artifacts)}")
    for clash in graph.artifact_contention(item["key"], by_key):
        print(
            f"⚠ merge contention on {', '.join(clash['artifacts'])} "
            f"with {clash['key']} [{clash['claimed_by']}]"
        )
    for ref in item.get("refs") or []:
        print(f"ref:     {ref}")
    if item.get("evidence"):
        print(f"\nevidence:\n{item['evidence'].rstrip()}")
    return 0


def _claim_projected(key: str, claim: dict[str, Any] | None) -> None:
    """Mirror a won/dropped claim into the committed file, and say what to do
    with it. Best-effort by design: the DB transaction already decided the race,
    so a projection failure must not read as a failed claim."""
    if write_claim_to_file(key, claim):
        print(f"projected into roadmap/items/{key}.yaml — run `sync`, then commit it")
    else:
        print(
            f"warning: no roadmap/items/{key}.yaml to project into, so this claim is "
            f"invisible to any agent in a checkout. Run `roadmap.py pull` first.",
            file=sys.stderr,
        )


def _contention_notice(key: str, by_key: dict[str, dict[str, Any]]) -> None:
    """Say who else is holding a counter this item will move.

    A warning and never a refusal. The two items are independent — that is the
    whole finding — so the cost is a rebase, and refusing the claim would
    serialize work that runs in parallel perfectly well. What it buys is that
    the second session learns at claim time rather than at review time, which is
    the difference #1103 paid four rebases for.
    """
    clashes = graph.artifact_contention(key, by_key)
    if not clashes:
        return
    print(
        f"\n⚠️  merge contention — {key} shares a mutable artifact with live claim(s). "
        f"Not a blocker: start it, but expect to rebase, and coordinate the counter.",
        file=sys.stderr,
    )
    for clash in clashes:
        print(
            f"    {', '.join(clash['artifacts'])}  ←  {clash['key']} "
            f"[{clash['claimed_by']}]",
            file=sys.stderr,
        )


def cmd_claim(args: argparse.Namespace) -> int:
    who = args.by or current_branch()
    stores = _stores()
    with store_for(_write_source(args)) as store:
        try:
            row = store.claim(args.key, by=who, force=args.force) or {}
        except stores.ClaimRefused as exc:
            # Losing a race is an ordinary outcome, so it is a refusal with the
            # holder's name and a non-zero exit — not a traceback. The API path
            # reaches this as an HTTPError turned SystemExit by `_api`, which
            # already prints the server's own message; only the local store
            # raises here.
            print(str(exc), file=sys.stderr)
            return 1
        print(f"claimed {args.key} for {who}")
        # Project the timestamp the STORE stamped, not this machine's clock. The
        # store returns the row it just committed, and that is the claim of
        # record; this used to stamp a client-side clock reading taken afterwards,
        # so the file recorded a time the store never held — and any skew
        # between a cloud session and the VM landed straight in the committed file.
        with switchboard_write_lock(args.key):
            _claim_projected(
                args.key,
                {"by": row.get("claimed_by") or who, "at": row.get("claimed_at")},
            )
        # State the exit at the entrance. A claim is the one roadmap act with no
        # natural end — `sync` is prompted by an edit and a PR is prompted by a
        # merge, but nothing ever asks a session whether it is still working. Say
        # here what "done" looks like, while somebody is reading.
        print(
            f"when you finish or stop: `roadmap.py release {args.key}` (or set it done "
            "and `prune`). An unreleased claim keeps the item off everyone's queue.",
            file=sys.stderr,
        )
        # Best-effort: the claim is already won, so a failed read here must not
        # turn a successful claim into a non-zero exit.
        try:
            live = store.items()
            _contention_notice(args.key, live)
            _own_claims_notice(live, exclude=args.key)
        except Exception:  # noqa: BLE001 - a nudge is never worth failing the claim
            pass
    return 0


def cmd_release(args: argparse.Namespace) -> int:
    with store_for(_write_source(args)) as store:
        store.release(args.key)
    print(f"released {args.key}")
    with switchboard_write_lock(args.key):
        _claim_projected(args.key, None)
    return 0


def cmd_impact(args: argparse.Namespace) -> int:
    """Did the fix hold? Linked tickets, split by which side of `done` they fall.

    Needs the store (and so a JWT): tickets live only in the DB, and an item's
    `done_at`/`done_version` are stamped by the transition, not authored in the
    file. There is no offline answer to give.
    """
    report = _api("GET", f"/admin/roadmap/{args.key}/impact") or {}
    print(f"{report.get('key')}  [{report.get('status')}]")
    print(f"  {report.get('title')}")
    done_at = report.get("done_at")
    if done_at:
        print(f"\ndone at   {graph.fmt_timestamp(done_at)}")
        print(f"prod then {report.get('done_version') or 'unknown'}")
        modules = report.get("done_modules") or {}
        if args.modules and modules:
            print("modules then:")
            for name in sorted(modules):
                print(f"  {name:<24} {modules[name]}")
    else:
        print("\nnot done — nothing has shipped, so no ticket can be 'after' it")

    tickets = report.get("tickets") or []
    if not tickets:
        print(
            "\nno linked tickets. Add `tickets:` to "
            f"roadmap/items/{args.key}.yaml and push."
        )
        return 0

    print(f"\n{len(tickets)} linked ticket(s):")
    for ticket in tickets:
        impact = ticket.get("impact", "?")
        marker = "!!" if impact == "after" else "  "
        text = " ".join((ticket.get("feedback_text") or "").split())[:88]
        print(
            f"{marker} {impact:<13} {graph.fmt_timestamp(ticket.get('created_at'))}"
            f"  [{ticket.get('source')}/{ticket.get('status')}]"
        )
        print(f"     {text}")
        if ticket.get("app_version"):
            print(f"     on {ticket['app_version']}")

    recurred = report.get("recurred_after_done") or 0
    if recurred:
        print(
            f"\n{recurred} ticket(s) filed AFTER this was marked done — the "
            "complaint recurred past the fix. That is the finding: the fix did "
            "not land, landed partially, or never reached the user."
        )
        # Non-zero so a CI job or a triage script can gate on it without
        # parsing the text above.
        return 2
    print("\nno recurrence after done")
    return 0


def cmd_validate(args: argparse.Namespace) -> int:
    by_key = load(args.source)
    arcs = load_arcs(args.source)
    problems = graph.validate_graph(by_key) + graph.validate_arcs(arcs, by_key)
    # Printed whether or not anything failed, and never fails the command. An
    # arc with no startable work is a coherent graph describing a thin backlog,
    # not a malformed one — failing hourly CI on it would make red the normal
    # state, which is how a guard stops being read. See `graph.arc_findings`.
    findings = graph.arc_findings(arcs, by_key)
    for finding in findings:
        print(f"finding: {finding}", file=sys.stderr)
    if not problems:
        print(
            f"ok — {len(by_key)} item(s), {len(arcs)} arc(s), no problems"
            + (f" ({len(findings)} finding(s), see above)" if findings else "")
        )
        return 0
    for problem in problems:
        print(f"error: {problem}", file=sys.stderr)
    return 1


def _add_source(parser: argparse.ArgumentParser) -> None:
    parser.add_argument(
        "--source", choices=("db", "files", "local"), default=_ENV_SOURCE or "files",
        help="where to read the graph from (default: files, no JWT needed; "
             "local reads the SQLite store, also no JWT)",
    )


def _add_store_source(parser: argparse.ArgumentParser, help_text: str) -> None:
    """Which *store* — never ``files``, for reasons that differ by command.

    Defaults to ``db`` unless the environment already said ``local``, because a
    silent change of destination is the worst possible default.
    """
    parser.add_argument(
        "--source", choices=("db", "local"),
        default=_ENV_SOURCE if _ENV_SOURCE == "local" else "db",
        help=help_text,
    )


def _add_write_source(parser: argparse.ArgumentParser) -> None:
    """The source for a command that WRITES.

    ``files`` is not offered at all: a claim decided by writing a file is the
    race that moving claims into a transaction eliminated, and offering it here
    would put it back within reach of a flag.
    """
    _add_store_source(parser, "which store to write to (default: db, the admin "
                              "API; local writes the SQLite store and needs no server)")


def _add_compared_source(parser: argparse.ArgumentParser) -> None:
    """The source for `diff` and `pull`, which read a store and touch files.

    ``files`` is not offered here for a different reason than above: both
    commands exist to reconcile a store *against* the files, so "files" is not
    a coherent answer to which store to use.

    These two read the store directly rather than through `load(source)`'s
    default, and until they took this flag they always reached for Lucille's
    admin API — so an adopter with `ROADMAP_SOURCE=local` set and no server at
    all was told to mint a JWT with a skill that does not exist in their
    project. That is the extraction's own seam left half-cut, and it is the one
    that matters most: `diff` is the assertion a sync workflow is built around.
    """
    _add_store_source(parser, "which store to compare the files against "
                              "(default: db, the admin API; local reads the "
                              "SQLite store and needs no server)")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = parser.add_subparsers(dest="command", required=True)

    p_sync = sub.add_parser("sync", help="regenerate roadmap/ROADMAP.md")
    _add_source(p_sync)
    p_sync.add_argument("--check", action="store_true",
                        help="exit 1 if the committed file is stale (for CI)")
    p_sync.set_defaults(func=cmd_sync)

    p_push = sub.add_parser("push", help="upload roadmap/items/*.yaml into a store")
    _add_write_source(p_push)
    p_push.set_defaults(func=cmd_push)

    p_pull = sub.add_parser(
        "pull", help="write store-only items and live claims back into roadmap/items/"
    )
    _add_compared_source(p_pull)
    p_pull.set_defaults(func=cmd_pull)

    p_diff = sub.add_parser(
        "diff", help="report where the store and the committed files disagree"
    )
    _add_compared_source(p_diff)
    p_diff.set_defaults(func=cmd_diff)

    p_prune = sub.add_parser("prune", help="delete done items from the store AND the files")
    p_prune.add_argument("--yes", action="store_true", help="actually delete (default: dry run)")
    p_prune.add_argument(
        "--allow-stale",
        action="store_true",
        help="prune even though roadmap/items/ disagrees with origin/main "
             "(you have read the difference and it is deliberate)",
    )
    p_prune.set_defaults(func=cmd_prune)

    p_refile = sub.add_parser(
        "refile", help="clear a pruned key's tombstone so it can be filed again"
    )
    p_refile.add_argument("key")
    p_refile.set_defaults(func=cmd_refile)

    p_list = sub.add_parser("list", help="all items grouped by status")
    _add_source(p_list)
    p_list.add_argument("--json", action="store_true")
    p_list.set_defaults(func=cmd_list)

    p_ready = sub.add_parser("ready", help="items startable right now")
    _add_source(p_ready)
    p_ready.set_defaults(func=cmd_ready)

    p_show = sub.add_parser("show", help="one item and its dependency chain")
    _add_source(p_show)
    p_show.add_argument("key")
    p_show.set_defaults(func=cmd_show)

    p_claim = sub.add_parser("claim", help="stake an item (DB transaction)")
    p_claim.add_argument("key")
    p_claim.add_argument("--by", help="defaults to the current git branch")
    p_claim.add_argument("--force", action="store_true", help="steal an existing claim")
    _add_write_source(p_claim)
    p_claim.set_defaults(func=cmd_claim)

    p_status = sub.add_parser("status", help="move an item's status (the store owns it)")
    p_status.add_argument("key")
    p_status.add_argument("status", choices=graph.STATUSES)
    _add_write_source(p_status)
    p_status.set_defaults(func=cmd_status)

    p_release = sub.add_parser("release", help="drop a claim")
    p_release.add_argument("key")
    _add_write_source(p_release)
    p_release.set_defaults(func=cmd_release)

    p_impact = sub.add_parser(
        "impact", help="linked tickets, before vs after this item was marked done"
    )
    p_impact.add_argument("key")
    p_impact.add_argument(
        "--modules", action="store_true",
        help="also print every installed module version at done time",
    )
    p_impact.set_defaults(func=cmd_impact)

    p_validate = sub.add_parser("validate", help="schema, dangling deps, cycles")
    _add_source(p_validate)
    p_validate.set_defaults(func=cmd_validate)

    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
